In [21]:
# for clean csv 

import pandas as pd

df1 = pd.read_csv("../data/balance_sheet.csv")
display(df1.head())

df2 = pd.read_csv("../data/cash_flow_statement.csv")
display(df2.head())

df3 = pd.read_csv("../data/income_statement.csv")
display(df3.head())

df4 = pd.read_csv("../data/metadata.csv")
display(df4.head())

,quarter,cash,accounts_receivable,inventory,ppe_net,total_assets,accounts_payable,short_term_debt,long_term_debt,total_liabilities,common_stock,retained_earnings,total_equity,total_liabilities_and_equity
0,2021-Q1,11184850.0,7280000.0,9962817.0,14208000.0,42635667.0,6849437.0,3200000,18000000,28049437.0,4561578.6,10024651.0,14586230.0,42635667.0
1,2021-Q2,15256100.0,7425600.0,10651038.0,14420160.0,47752898.0,7322589.0,3200000,17880000,28402589.0,4561578.6,14788730.0,19350309.0,47752898.0
2,2021-Q3,20400957.0,7571200.0,10670628.0,14636480.0,53279265.0,7336057.0,3200000,17760000,28296057.0,4561578.6,20421629.0,24983208.0,53279265.0
3,2021-Q4,25504298.0,8008000.0,11164212.0,14865280.0,59541790.0,7675396.0,3200000,17640000,28515396.0,4561578.6,26464815.0,31026394.0,59541790.0
4,2022-Q1,32399174.0,7644000.0,10270058.0,15083680.0,65396912.0,7060665.0,3200000,17520000,27780665.0,4561578.6,33054668.0,37616247.0,65396912.0

,quarter,net_income,depreciation,change_in_ar,change_in_inventory,change_in_ap,cash_from_operations,capital_expenditures,cash_from_investing,dividends_paid,debt_repayment,cash_from_financing,net_change_in_cash,ending_cash_balance
0,2021-Q1,6344651.0,728000.0,-218400.0,-298885.0,205483.0,6760850.0,-936000.0,-936000.0,-320000,-120000,-440000,5384850.0,11184850.0
1,2021-Q2,5084079.0,742560.0,-145600.0,-688221.0,473152.0,5465970.0,-954720.0,-954720.0,-320000,-120000,-440000,4071250.0,15256100.0
2,2021-Q3,5952899.0,757120.0,-145600.0,-19590.0,13468.0,6558297.0,-973440.0,-973440.0,-320000,-120000,-440000,5144857.0,20400957.0
3,2021-Q4,6363186.0,800800.0,-436800.0,-493584.0,339339.0,6572941.0,-1029600.0,-1029600.0,-320000,-120000,-440000,5103341.0,25504298.0
4,2022-Q1,6909853.0,764400.0,364000.0,894154.0,-614731.0,8317676.0,-982800.0,-982800.0,-320000,-120000,-440000,6894876.0,32399174.0

,quarter,revenue,cogs,gross_profit,marketing_expense,logistics_expense,it_expense,ga_expense,payroll_expense,total_operating_expense,operating_income,interest_expense,pretax_income,tax_expense,net_income
0,2021-Q1,52000000.0,31133804.0,20866196.0,1522714.0,3443460.0,652845.0,2528814.0,4436343.0,12584176.0,8282020.0,386105,7895915.0,1551264.0,6344651.0
1,2021-Q2,53040000.0,33284494.0,19755506.0,1377791.0,3710242.0,641009.0,2452197.0,4845952.0,13027191.0,6728315.0,370230,6358085.0,1274006.0,5084079.0
2,2021-Q3,54080000.0,33345712.0,20734288.0,1462594.0,3533797.0,774152.0,2342150.0,4766804.0,12879497.0,7854791.0,375707,7479084.0,1526185.0,5952899.0
3,2021-Q4,57200000.0,34888163.0,22311837.0,1576691.0,4238131.0,710825.0,2324355.0,5152902.0,14002904.0,8308933.0,381976,7926957.0,1563771.0,6363186.0
4,2022-Q1,54600000.0,32093931.0,22506069.0,1539310.0,3690294.0,661956.0,2353796.0,5136531.0,13381887.0,9124182.0,383776,8740406.0,1830553.0,6909853.0

,doc_id,filename,title,doc_type,role_tier,department,sensitivity,notes
0,1,cfo_company_summary_q3.txt,Q3 Company-Wide Financial Summary,narrative,exec,executive,high,clean
1,2,treasury_cashflow_report_q3.txt,Q3 Cash Flow and Investment Report,narrative,manager,treasury,medium,clean
2,3,fpa_budget_vs_actuals_q3.txt,Q3 Budget vs Actuals by Department,narrative,manager,fpa,medium,clean
3,4,tax_filing_summary_q3.txt,Q3 Tax Filing and Compliance Summary,narrative,staff,tax,low,clean
4,5,payroll_processing_log_q3.txt,Q3 Payroll Processing Log,narrative,staff,accounting,low,clean

In [27]:
# for messy dataset 

import pandas as pd

messy = pd.read_csv("../data/messy_data/income_statement_RAW_export.csv")
messy.head()

,Period,Rev,NetInc,OpInc,Notes
0,Q1 2021,"$52,000,000","6,344,651",8282020.0,manual adjustment pending review
1,Q2 2021,"$53,040,000","5,084,079",6728315.0,NaN
2,Q3 2021,"$54,080,000","5,952,899",7854791.0,NaN
3,Q4 2021,"$57,200,000","6,363,186",8308933.0,NaN
4,Q1 2022,"$54,600,000","6,909,853",9124182.0,NaN

In [31]:
# reading .txt files 

with open("../data/messy_data/fpa_expense_summary_q2_2023_BROKEN_FORMAT.txt") as f:
    content = f.read()
print(content)

FICTIONAL COMPANY: Nexora Retail Holdings Inc.
DOCUMENT: Q2 2023 Departmental Expense Summary
ACCESS LEVEL: Manager tier (FP&A department)
PREPARED BY: FP&A Manager
[SOURCE: exported from legacy PDF report - table formatting degraded on conversion]


Department        Budget      Actual    Variance
Marketing          2,100,000    2,290,000       -190,000
Logisti
cs             6,050,000    5,830,000        220,000
IT                 980,00 0     1,045,000        -65,000
Accounting&Tax    1,520,000    1,498,00 0         22,000


Note: table columns misaligned due to source PDF conversion artifact -
common when ingesting legacy department reports exported before the 2023
system migration. Notice department name "Logistics" is broken across two
lines, and numeric values have stray spaces inserted mid-number. A production
chunking/preprocessing step needs to normalize this before embedding,
otherwise retrieval quality on this document will be poor.

In [42]:
df_info1 = pd.read_csv("../data/balance_sheet.csv")
df_info1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   quarter                       20 non-null     object
 1   cash                          20 non-null     float64
 2   accounts_receivable           20 non-null     float64
 3   inventory                     20 non-null     float64
 4   ppe_net                       20 non-null     float64
 5   total_assets                  20 non-null     float64
 6   accounts_payable              20 non-null     float64
 7   short_term_debt               20 non-null     int64
 8   long_term_debt                20 non-null     int64
 9   total_liabilities             20 non-null     float64
 10  common_stock                  20 non-null     float64
 11  retained_earnings             20 non-null     float64
 12  total_equity                  20 non-null     float64
 13  total_liabilities_and_equity  20 non-null     float64
dtypes: float64(11), int64(2), object(1)
memory usage: 2.3+ KB

In [44]:
df_info2 = pd.read_csv("../data/cash_flow_statement.csv")
df_info2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   quarter               20 non-null     object
 1   net_income            20 non-null     float64
 2   depreciation          20 non-null     float64
 3   change_in_ar          20 non-null     float64
 4   change_in_inventory   20 non-null     float64
 5   change_in_ap          20 non-null     float64
 6   cash_from_operations  20 non-null     float64
 7   capital_expenditures  20 non-null     float64
 8   cash_from_investing   20 non-null     float64
 9   dividends_paid        20 non-null     int64
 10  debt_repayment        20 non-null     int64
 11  cash_from_financing   20 non-null     int64
 12  net_change_in_cash    20 non-null     float64
 13  ending_cash_balance   20 non-null     float64
dtypes: float64(10), int64(3), object(1)
memory usage: 2.3+ KB

In [45]:
df_info3 = pd.read_csv("../data/income_statement.csv")
df_info3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   quarter                  20 non-null     object
 1   revenue                  20 non-null     float64
 2   cogs                     20 non-null     float64
 3   gross_profit             20 non-null     float64
 4   marketing_expense        20 non-null     float64
 5   logistics_expense        20 non-null     float64
 6   it_expense               20 non-null     float64
 7   ga_expense               20 non-null     float64
 8   payroll_expense          20 non-null     float64
 9   total_operating_expense  20 non-null     float64
 10  operating_income         20 non-null     float64
 11  interest_expense         20 non-null     int64
 12  pretax_income            20 non-null     float64
 13  tax_expense              20 non-null     float64
 14  net_income               20 non-null     float64
dtypes: float64(13), int64(1), object(1)
memory usage: 2.5+ KB

In [46]:
df_info4 = pd.read_csv("../data/metadata.csv")
df_info4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   doc_id       13 non-null     int64
 1   filename     13 non-null     object
 2   title        13 non-null     object
 3   doc_type     13 non-null     object
 4   role_tier    11 non-null     object
 5   department   12 non-null     object
 6   sensitivity  13 non-null     object
 7   notes        13 non-null     object
dtypes: int64(1), object(7)
memory usage: 960.0+ bytes

In [47]:
df_info5 = pd.read_csv("../data/messy_data/income_statement_RAW_export.csv")
df_info5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Period  21 non-null     object
 1   Rev     21 non-null     object
 2   NetInc  21 non-null     object
 3   OpInc   20 non-null     float64
 4   Notes   15 non-null     object
dtypes: float64(1), object(4)
memory usage: 968.0+ bytes

In [48]:
df_des1 = pd.read_csv("../data/balance_sheet.csv")
df_des1.describe()

,cash,accounts_receivable,inventory,ppe_net,total_assets,accounts_payable,short_term_debt,long_term_debt,total_liabilities,common_stock,retained_earnings,total_equity,total_liabilities_and_equity
count,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,20.0,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01
mean,6.578397e+07,8.921640e+06,1.228582e+07,1.644275e+07,1.034342e+08,8.446498e+06,3200000.0,1.686000e+07,2.850650e+07,4.561579e+06,7.036610e+07,7.492768e+07,1.034342e+08
std,3.688357e+07,1.548736e+06,2.090266e+06,1.498843e+06,4.183742e+07,1.437058e+06,0.0,7.099296e+05,8.285026e+05,1.911034e-09,4.118689e+07,4.118689e+07,4.183742e+07
min,1.118485e+07,7.134400e+06,9.585368e+06,1.420800e+07,4.263567e+07,6.589940e+06,3200000.0,1.572000e+07,2.718994e+07,4.561579e+06,1.002465e+07,1.458623e+07,4.263567e+07
25%,3.724950e+07,7.625800e+06,1.066573e+07,1.523656e+07,6.950440e+07,7.332690e+06,3200000.0,1.629000e+07,2.789615e+07,4.561579e+06,3.760520e+07,4.216678e+07,6.950440e+07
50%,6.357605e+07,8.226400e+06,1.149162e+07,1.630880e+07,9.926918e+07,7.900486e+06,3200000.0,1.686000e+07,2.845899e+07,4.561579e+06,6.695150e+07,7.151308e+07,9.926918e+07
75%,9.261448e+07,9.991800e+06,1.345941e+07,1.757760e+07,1.336383e+08,9.253342e+06,3200000.0,1.743000e+07,2.892334e+07,4.561579e+06,1.003368e+08,1.048984e+08,1.336383e+08
max,1.324948e+08,1.215760e+07,1.652215e+07,1.909808e+07,1.802727e+08,1.135898e+07,3200000.0,1.800000e+07,3.027898e+07,4.561579e+06,1.454321e+08,1.499937e+08,1.802727e+08

In [50]:
df_des2 = pd.read_csv("../data/messy_data/income_statement_RAW_export.csv")
df_des2.describe()

              OpInc
count  2.000000e+01
mean   9.623108e+06
std    2.088511e+06
min    6.728315e+06
25%    8.226052e+06
50%    8.804026e+06
75%    1.063642e+07
max    1.443006e+07