In [1]:
# for clean csv 

import pandas as pd

df1 = pd.read_csv("../data/balance_sheet.csv")
display(df1.head())

df2 = pd.read_csv("../data/cash_flow_statement.csv")
display(df2.head())

df3 = pd.read_csv("../data/income_statement.csv")
display(df3.head())

df4 = pd.read_csv("../data/metadata.csv")
display(df4.head())

,quarter,cash,accounts_receivable,inventory,ppe_net,total_assets,accounts_payable,short_term_debt,long_term_debt,total_liabilities,common_stock,retained_earnings,total_equity,total_liabilities_and_equity
0,2021-Q1,11184850.0,7280000.0,9962817.0,14208000.0,42635667.0,6849437.0,3200000,18000000,28049437.0,4561578.6,10024651.0,14586230.0,42635667.0
1,2021-Q2,15256100.0,7425600.0,10651038.0,14420160.0,47752898.0,7322589.0,3200000,17880000,28402589.0,4561578.6,14788730.0,19350309.0,47752898.0
2,2021-Q3,20400957.0,7571200.0,10670628.0,14636480.0,53279265.0,7336057.0,3200000,17760000,28296057.0,4561578.6,20421629.0,24983208.0,53279265.0
3,2021-Q4,25504298.0,8008000.0,11164212.0,14865280.0,59541790.0,7675396.0,3200000,17640000,28515396.0,4561578.6,26464815.0,31026394.0,59541790.0
4,2022-Q1,32399174.0,7644000.0,10270058.0,15083680.0,65396912.0,7060665.0,3200000,17520000,27780665.0,4561578.6,33054668.0,37616247.0,65396912.0

,quarter,net_income,depreciation,change_in_ar,change_in_inventory,change_in_ap,cash_from_operations,capital_expenditures,cash_from_investing,dividends_paid,debt_repayment,cash_from_financing,net_change_in_cash,ending_cash_balance
0,2021-Q1,6344651.0,728000.0,-218400.0,-298885.0,205483.0,6760850.0,-936000.0,-936000.0,-320000,-120000,-440000,5384850.0,11184850.0
1,2021-Q2,5084079.0,742560.0,-145600.0,-688221.0,473152.0,5465970.0,-954720.0,-954720.0,-320000,-120000,-440000,4071250.0,15256100.0
2,2021-Q3,5952899.0,757120.0,-145600.0,-19590.0,13468.0,6558297.0,-973440.0,-973440.0,-320000,-120000,-440000,5144857.0,20400957.0
3,2021-Q4,6363186.0,800800.0,-436800.0,-493584.0,339339.0,6572941.0,-1029600.0,-1029600.0,-320000,-120000,-440000,5103341.0,25504298.0
4,2022-Q1,6909853.0,764400.0,364000.0,894154.0,-614731.0,8317676.0,-982800.0,-982800.0,-320000,-120000,-440000,6894876.0,32399174.0

,quarter,revenue,cogs,gross_profit,marketing_expense,logistics_expense,it_expense,ga_expense,payroll_expense,total_operating_expense,operating_income,interest_expense,pretax_income,tax_expense,net_income
0,2021-Q1,52000000.0,31133804.0,20866196.0,1522714.0,3443460.0,652845.0,2528814.0,4436343.0,12584176.0,8282020.0,386105,7895915.0,1551264.0,6344651.0
1,2021-Q2,53040000.0,33284494.0,19755506.0,1377791.0,3710242.0,641009.0,2452197.0,4845952.0,13027191.0,6728315.0,370230,6358085.0,1274006.0,5084079.0
2,2021-Q3,54080000.0,33345712.0,20734288.0,1462594.0,3533797.0,774152.0,2342150.0,4766804.0,12879497.0,7854791.0,375707,7479084.0,1526185.0,5952899.0
3,2021-Q4,57200000.0,34888163.0,22311837.0,1576691.0,4238131.0,710825.0,2324355.0,5152902.0,14002904.0,8308933.0,381976,7926957.0,1563771.0,6363186.0
4,2022-Q1,54600000.0,32093931.0,22506069.0,1539310.0,3690294.0,661956.0,2353796.0,5136531.0,13381887.0,9124182.0,383776,8740406.0,1830553.0,6909853.0

,doc_id,filename,title,doc_type,role_tier,department,sensitivity,notes
0,1,cfo_company_summary_q3.txt,Q3 Company-Wide Financial Summary,narrative,exec,executive,high,clean
1,2,treasury_cashflow_report_q3.txt,Q3 Cash Flow and Investment Report,narrative,manager,treasury,medium,clean
2,3,fpa_budget_vs_actuals_q3.txt,Q3 Budget vs Actuals by Department,narrative,manager,fpa,medium,clean
3,4,tax_filing_summary_q3.txt,Q3 Tax Filing and Compliance Summary,narrative,staff,tax,low,clean
4,5,payroll_processing_log_q3.txt,Q3 Payroll Processing Log,narrative,staff,accounting,low,clean

In [2]:
# for messy dataset 

import pandas as pd

messy = pd.read_csv("../data/messy_data/income_statement_RAW_export.csv")
messy.head()

,Period,Rev,NetInc,OpInc,Notes
0,Q1 2021,"$52,000,000","6,344,651",8282020.0,manual adjustment pending review
1,Q2 2021,"$53,040,000","5,084,079",6728315.0,NaN
2,Q3 2021,"$54,080,000","5,952,899",7854791.0,NaN
3,Q4 2021,"$57,200,000","6,363,186",8308933.0,NaN
4,Q1 2022,"$54,600,000","6,909,853",9124182.0,NaN

In [3]:
# reading .txt files 

with open("../data/messy_data/fpa_expense_summary_q2_2023_BROKEN_FORMAT.txt") as f:
    content = f.read()
print(content)

FICTIONAL COMPANY: Nexora Retail Holdings Inc.
DOCUMENT: Q2 2023 Departmental Expense Summary
ACCESS LEVEL: Manager tier (FP&A department)
PREPARED BY: FP&A Manager
[SOURCE: exported from legacy PDF report - table formatting degraded on conversion]


Department        Budget      Actual    Variance
Marketing          2,100,000    2,290,000       -190,000
Logisti
cs             6,050,000    5,830,000        220,000
IT                 980,00 0     1,045,000        -65,000
Accounting&Tax    1,520,000    1,498,00 0         22,000


Note: table columns misaligned due to source PDF conversion artifact -
common when ingesting legacy department reports exported before the 2023
system migration. Notice department name "Logistics" is broken across two
lines, and numeric values have stray spaces inserted mid-number. A production
chunking/preprocessing step needs to normalize this before embedding,
otherwise retrieval quality on this document will be poor.

In [4]:
df_info1 = pd.read_csv("../data/balance_sheet.csv")
df_info1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   quarter                       20 non-null     object
 1   cash                          20 non-null     float64
 2   accounts_receivable           20 non-null     float64
 3   inventory                     20 non-null     float64
 4   ppe_net                       20 non-null     float64
 5   total_assets                  20 non-null     float64
 6   accounts_payable              20 non-null     float64
 7   short_term_debt               20 non-null     int64
 8   long_term_debt                20 non-null     int64
 9   total_liabilities             20 non-null     float64
 10  common_stock                  20 non-null     float64
 11  retained_earnings             20 non-null     float64
 12  total_equity                  20 non-null     float64
 13  total_liabilities_and_equity  20 non-null     float64
dtypes: float64(11), int64(2), object(1)
memory usage: 2.3+ KB

In [5]:
df_info2 = pd.read_csv("../data/cash_flow_statement.csv")
df_info2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   quarter               20 non-null     object
 1   net_income            20 non-null     float64
 2   depreciation          20 non-null     float64
 3   change_in_ar          20 non-null     float64
 4   change_in_inventory   20 non-null     float64
 5   change_in_ap          20 non-null     float64
 6   cash_from_operations  20 non-null     float64
 7   capital_expenditures  20 non-null     float64
 8   cash_from_investing   20 non-null     float64
 9   dividends_paid        20 non-null     int64
 10  debt_repayment        20 non-null     int64
 11  cash_from_financing   20 non-null     int64
 12  net_change_in_cash    20 non-null     float64
 13  ending_cash_balance   20 non-null     float64
dtypes: float64(10), int64(3), object(1)
memory usage: 2.3+ KB

In [6]:
df_info3 = pd.read_csv("../data/income_statement.csv")
df_info3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   quarter                  20 non-null     object
 1   revenue                  20 non-null     float64
 2   cogs                     20 non-null     float64
 3   gross_profit             20 non-null     float64
 4   marketing_expense        20 non-null     float64
 5   logistics_expense        20 non-null     float64
 6   it_expense               20 non-null     float64
 7   ga_expense               20 non-null     float64
 8   payroll_expense          20 non-null     float64
 9   total_operating_expense  20 non-null     float64
 10  operating_income         20 non-null     float64
 11  interest_expense         20 non-null     int64
 12  pretax_income            20 non-null     float64
 13  tax_expense              20 non-null     float64
 14  net_income               20 non-null     float64
dtypes: float64(13), int64(1), object(1)
memory usage: 2.5+ KB

In [7]:
df_info4 = pd.read_csv("../data/metadata.csv")
df_info4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   doc_id       13 non-null     int64
 1   filename     13 non-null     object
 2   title        13 non-null     object
 3   doc_type     13 non-null     object
 4   role_tier    11 non-null     object
 5   department   12 non-null     object
 6   sensitivity  13 non-null     object
 7   notes        13 non-null     object
dtypes: int64(1), object(7)
memory usage: 960.0+ bytes

In [8]:
df_info5 = pd.read_csv("../data/messy_data/income_statement_RAW_export.csv")
df_info5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Period  21 non-null     object
 1   Rev     21 non-null     object
 2   NetInc  21 non-null     object
 3   OpInc   20 non-null     float64
 4   Notes   15 non-null     object
dtypes: float64(1), object(4)
memory usage: 968.0+ bytes

In [9]:
df_des1 = pd.read_csv("../data/balance_sheet.csv")
df_des1.describe()

,cash,accounts_receivable,inventory,ppe_net,total_assets,accounts_payable,short_term_debt,long_term_debt,total_liabilities,common_stock,retained_earnings,total_equity,total_liabilities_and_equity
count,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,20.0,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01
mean,6.578397e+07,8.921640e+06,1.228582e+07,1.644275e+07,1.034342e+08,8.446498e+06,3200000.0,1.686000e+07,2.850650e+07,4.561579e+06,7.036610e+07,7.492768e+07,1.034342e+08
std,3.688357e+07,1.548736e+06,2.090266e+06,1.498843e+06,4.183742e+07,1.437058e+06,0.0,7.099296e+05,8.285026e+05,1.911034e-09,4.118689e+07,4.118689e+07,4.183742e+07
min,1.118485e+07,7.134400e+06,9.585368e+06,1.420800e+07,4.263567e+07,6.589940e+06,3200000.0,1.572000e+07,2.718994e+07,4.561579e+06,1.002465e+07,1.458623e+07,4.263567e+07
25%,3.724950e+07,7.625800e+06,1.066573e+07,1.523656e+07,6.950440e+07,7.332690e+06,3200000.0,1.629000e+07,2.789615e+07,4.561579e+06,3.760520e+07,4.216678e+07,6.950440e+07
50%,6.357605e+07,8.226400e+06,1.149162e+07,1.630880e+07,9.926918e+07,7.900486e+06,3200000.0,1.686000e+07,2.845899e+07,4.561579e+06,6.695150e+07,7.151308e+07,9.926918e+07
75%,9.261448e+07,9.991800e+06,1.345941e+07,1.757760e+07,1.336383e+08,9.253342e+06,3200000.0,1.743000e+07,2.892334e+07,4.561579e+06,1.003368e+08,1.048984e+08,1.336383e+08
max,1.324948e+08,1.215760e+07,1.652215e+07,1.909808e+07,1.802727e+08,1.135898e+07,3200000.0,1.800000e+07,3.027898e+07,4.561579e+06,1.454321e+08,1.499937e+08,1.802727e+08

In [10]:
df_des2 = pd.read_csv("../data/messy_data/income_statement_RAW_export.csv")
df_des2.describe()

              OpInc
count  2.000000e+01
mean   9.623108e+06
std    2.088511e+06
min    6.728315e+06
25%    8.226052e+06
50%    8.804026e+06
75%    1.063642e+07
max    1.443006e+07

In [11]:
# filling in missing values in messy data folder (CSV)

messy["OpInc"] = messy["OpInc"].interpolate()
messy["Notes"] = messy["Notes"].fillna(messy["Notes"].mode()[0])
messy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Period  21 non-null     object
 1   Rev     21 non-null     object
 2   NetInc  21 non-null     object
 3   OpInc   21 non-null     float64
 4   Notes   21 non-null     object
dtypes: float64(1), object(4)
memory usage: 968.0+ bytes

In [12]:
# cleaning the messy data folder values (CSV)

messy["Rev"] = messy["Rev"].str.replace("$", "", regex= False)
messy["Rev"] = messy["Rev"].str.replace(",", "", regex= False)
messy["Rev"] = messy["Rev"].str.strip()
messy["Rev"] = pd.to_numeric(messy["Rev"])

In [13]:
messy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Period  21 non-null     object
 1   Rev     21 non-null     float64
 2   NetInc  21 non-null     object
 3   OpInc   21 non-null     float64
 4   Notes   21 non-null     object
dtypes: float64(2), object(3)
memory usage: 968.0+ bytes

In [14]:
messy["NetInc"] = messy["NetInc"].str.replace(",", "", regex=False)
messy["NetInc"] = messy["NetInc"].str.strip()
messy["NetInc"] = pd.to_numeric(messy["NetInc"])

In [15]:
messy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Period  21 non-null     object
 1   Rev     21 non-null     float64
 2   NetInc  21 non-null     float64
 3   OpInc   21 non-null     float64
 4   Notes   21 non-null     object
dtypes: float64(3), object(2)
memory usage: 968.0+ bytes

In [16]:
print(messy.info())
print(messy.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Period  21 non-null     object
 1   Rev     21 non-null     float64
 2   NetInc  21 non-null     float64
 3   OpInc   21 non-null     float64
 4   Notes   21 non-null     object
dtypes: float64(3), object(2)
memory usage: 968.0+ bytes
None
                Rev        NetInc         OpInc
count  2.100000e+01  2.100000e+01  2.100000e+01
mean   6.351429e+07  1.167075e+07  9.684836e+06
std    1.082585e+07  1.986265e+07  2.055189e+06
min    5.096000e+07  5.084079e+06  6.728315e+06
25%    5.460000e+07  6.304103e+06  8.282020e+06
50%    5.928000e+07  6.909853e+06  9.124182e+06
75%    7.020000e+07  8.382157e+06  1.091940e+07
max    8.684000e+07  9.808000e+07  1.443006e+07

In [17]:
import numpy as np

messy.loc[messy["NetInc"] > 90000000, "NetInc"] = np.nan
messy["NetInc"] = messy["NetInc"].interpolate()

In [18]:
messy.describe()

                Rev        NetInc         OpInc
count  2.100000e+01  2.100000e+01  2.100000e+01
mean   6.351429e+07  7.426178e+06  9.684836e+06
std    1.082585e+07  1.628395e+06  2.055189e+06
min    5.096000e+07  5.084079e+06  6.728315e+06
25%    5.460000e+07  6.304103e+06  8.282020e+06
50%    5.928000e+07  6.909853e+06  9.124182e+06
75%    7.020000e+07  8.382157e+06  1.091940e+07
max    8.684000e+07  1.104194e+07  1.443006e+07

In [19]:
def clean_period(months):
    parts = months.split()
    if parts[0] == "Q1":
        return parts[1] + "-01-01"
    elif parts[0] == "Q2":
        return parts[1] + "-04-01"
    elif parts[0] == "Q3":
        return parts[1] + "-07-01"
    elif parts[0] == "Q4":
        return parts[1] + "-10-01"
    else:
        return months 

messy["Period"] = messy["Period"].apply(clean_period)

In [20]:
messy[messy.duplicated()]
messy = messy.drop_duplicates()

In [21]:
messy

,Period,Rev,NetInc,OpInc,Notes
0,2021-01-01,52000000.0,6344651.0,8282020.0,manual adjustment pending review
1,2021-04-01,53040000.0,5084079.0,6728315.0,reconciled
2,2021-07-01,54080000.0,5952899.0,7854791.0,reconciled
3,2021-10-01,57200000.0,6363186.0,8308933.0,reconciled
4,2022-01-01,54600000.0,6909853.0,9124182.0,reconciled
5,2022-04-01,50960000.0,6387372.0,8467682.0,manual adjustment pending review
6,2022-07-01,53560000.0,7237597.0,9352508.0,reconciled
7,2022-10-01,58240000.0,5519357.0,7265498.0,reconciled
8,2023-01-01,56160000.0,6091322.0,8023688.0,reconciled
9,2023-04-01,57720000.0,6478176.0,8483870.0,reconciled
10,2023-07-01,59280000.0,7886016.0,10186656.0,reconciled
11,2023-10-01,63440000.0,6089370.0,8058149.0,reconciled
12,2024-01-01,66560000.0,6304103.0,8359976.0,reconciled
13,2024-04-01,68640000.0,8008553.0,10353434.0,reconciled
14,2024-07-01,70200000.0,8382157.0,10919401.5,reconciled
15,2024-10-01,74880000.0,8944039.0,11485369.0,reconciled
16,2025-01-01,76960000.0,9505921.0,12269081.0,reconciled
17,2025-04-01,79040000.0,9759085.0,12542175.0,reconciled
18,2025-07-01,81120000.0,9774051.0,12699109.0,reconciled
19,2025-10-01,86840000.0,11041942.0,14430060.0,reconciled

In [22]:
# fixing messy .txt files 

content = content.replace("Logisti\ncs", "Logistics")
content = content.replace("980,00 0", "980,000")
content = content.replace("1,498,00 0", "1,498,000")
print(content)

FICTIONAL COMPANY: Nexora Retail Holdings Inc.
DOCUMENT: Q2 2023 Departmental Expense Summary
ACCESS LEVEL: Manager tier (FP&A department)
PREPARED BY: FP&A Manager
[SOURCE: exported from legacy PDF report - table formatting degraded on conversion]


Department        Budget      Actual    Variance
Marketing          2,100,000    2,290,000       -190,000
Logistics             6,050,000    5,830,000        220,000
IT                 980,000     1,045,000        -65,000
Accounting&Tax    1,520,000    1,498,000         22,000


Note: table columns misaligned due to source PDF conversion artifact -
common when ingesting legacy department reports exported before the 2023
system migration. Notice department name "Logistics" is broken across two
lines, and numeric values have stray spaces inserted mid-number. A production
chunking/preprocessing step needs to normalize this before embedding,
otherwise retrieval quality on this document will be poor.

Chunking -> Embedding -> Store & compare

In [34]:
with open("../data/business_intelligence_market_trends_q3.txt") as f:
    content_1 = f.read()
print(content_1)

FICTIONAL COMPANY: Nexora Retail Holdings Inc.
DOCUMENT: Q3 Market Trends and Competitive Analysis
ACCESS LEVEL: Staff tier (Business Intelligence function)
PREPARED BY: Business Intelligence Analyst

--- INTERNAL: BUSINESS PARTNERING & BI DISTRIBUTION ---

Market share in core Northeast segment estimated at 14.2%, up 0.6 points from
Q2, primarily at the expense of a regional competitor that closed two stores
this quarter.

Customer churn rate: 3.1% quarterly, down from 3.6% in Q2. Improvement linked
to the new loyalty program launched in July.

Competitive pricing analysis: our average basket price remains 4% above the
nearest competitor, with no significant impact on conversion observed to date.

Emerging trend: online order volume grew 22% quarter-over-quarter, now
representing 31% of total revenue, up from 27% in Q2.

Recommendation: propose increased marketing spend allocation toward digital
channels in Q4 planning, pending FP&A budget review.

In [35]:
chunks = content_1.split("\n\n")
print(chunks)

['FICTIONAL COMPANY: Nexora Retail Holdings Inc.\nDOCUMENT: Q3 Market Trends and Competitive Analysis\nACCESS LEVEL: Staff tier (Business Intelligence function)\nPREPARED BY: Business Intelligence Analyst', '--- INTERNAL: BUSINESS PARTNERING & BI DISTRIBUTION ---', 'Market share in core Northeast segment estimated at 14.2%, up 0.6 points from\nQ2, primarily at the expense of a regional competitor that closed two stores\nthis quarter.', 'Customer churn rate: 3.1% quarterly, down from 3.6% in Q2. Improvement linked\nto the new loyalty program launched in July.', 'Competitive pricing analysis: our average basket price remains 4% above the\nnearest competitor, with no significant impact on conversion observed to date.', 'Emerging trend: online order volume grew 22% quarter-over-quarter, now\nrepresenting 31% of total revenue, up from 27% in Q2.', 'Recommendation: propose increased marketing spend allocation toward digital\nchannels in Q4 planning, pending FP&A budget review.\n']

In [39]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\Users\ASUS\OneDrive\Desktop\financial-assistant-rbac\financial-assistant-rbac\venv\lib\site-packages\huggingface_hub\file_download.py:150: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ASUS\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

c:\Users\ASUS\OneDrive\Desktop\financial-assistant-rbac\financial-assistant-rbac\venv\lib\site-packages\huggingface_hub\file_download.py:150: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ASUS\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [42]:
vector = model.encode(chunks)
print(len(vector))

7

In [44]:
import chromadb

client = chromadb.Client()
collection = client.create_collection(name = "Nexora_documents")

In [46]:
collection.add(
    documents = chunks, 
    embeddings= vector.tolist(),
    ids = [f"chunks_{i}" for i in range (len(chunks)) ]
)

In [48]:
results = collection.query(
    query_embeddings=model.encode(["What is the customer churn rate?"]).tolist(),
    n_results = 2
)
print(results)

{'ids': [['chunks_3', 'chunks_2']], 'embeddings': None, 'documents': [['Customer churn rate: 3.1% quarterly, down from 3.6% in Q2. Improvement linked\nto the new loyalty program launched in July.', 'Market share in core Northeast segment estimated at 14.2%, up 0.6 points from\nQ2, primarily at the expense of a regional competitor that closed two stores\nthis quarter.']], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[None, None]], 'distances': [[0.406521737575531, 1.3368144035339355]]}